import { Tool } from './types';

export const toolColors: Record<string, { light: string; dark: string; gradient: string }> = {
  purple: { light: 'rgba(139, 92, 246, 0.3)', dark: '#7c3aed', gradient: 'linear-gradient(135deg, #8b5cf6, #7c3aed)' },
  orange: { light: 'rgba(249, 115, 22, 0.3)', dark: '#ea580c', gradient: 'linear-gradient(135deg, #f97316, #ea580c)' },
  pink: { light: 'rgba(236, 72, 153, 0.3)', dark: '#db2777', gradient: 'linear-gradient(135deg, #ec4899, #db2777)' },
  cyan: { light: 'rgba(6, 182, 212, 0.3)', dark: '#0891b2', gradient: 'linear-gradient(135deg, #06b6d4, #0891b2)' },
  green: { light: 'rgba(16, 185, 129, 0.3)', dark: '#059669', gradient: 'linear-gradient(135deg, #10b981, #059669)' },
  blue: { light: 'rgba(59, 130, 246, 0.3)', dark: '#2563eb', gradient: 'linear-gradient(135deg, #3b82f6, #2563eb)' },
  red: { light: 'rgba(239, 68, 68, 0.3)', dark: '#dc2626', gradient: 'linear-gradient(135deg, #ef4444, #dc2626)' },
  yellow: { light: 'rgba(234, 179, 8, 0.3)', dark: '#ca8a04', gradient: 'linear-gradient(135deg, #eab308, #ca8a04)' },
  emerald: { light: 'rgba(16, 185, 129, 0.3)', dark: '#059669', gradient: 'linear-gradient(135deg, #10b981, #059669)' },
  violet: { light: 'rgba(139, 92, 246, 0.3)', dark: '#7c3aed', gradient: 'linear-gradient(135deg, #8b5cf6, #7c3aed)' },
  indigo: { light: 'rgba(99, 102, 241, 0.3)', dark: '#4f46e5', gradient: 'linear-gradient(135deg, #6366f1, #4f46e5)' },
  teal: { light: 'rgba(20, 184, 166, 0.3)', dark: '#0d9488', gradient: 'linear-gradient(135deg, #14b8a6, #0d9488)' },
};

export const TOOLS: Tool[] = [
  // Image Converters (7)
  {
    id: 'image-compress',
    name: 'Image Compress',
    label: 'Squeeze',
    description: 'Reduce image file size while maintaining quality.',
    icon: 'compress',
    inputFormats: ['jpg', 'jpeg', 'png', 'webp', 'gif'],
    outputFormat: 'jpg',
    category: 'image',
    apiEndpoint: '/api/convert',
    color: 'purple',
  },
  {
    id: 'jpg-to-webp',
    name: 'JPG to WebP',
    label: 'Compress',
    description: 'Convert JPG to WebP for smaller file sizes.',
    icon: 'jpg-webp',
    inputFormats: ['jpg', 'jpeg'],
    outputFormat: 'webp',
    category: 'image',
    apiEndpoint: '/api/convert',
    color: 'orange',
  },
  {
    id: 'webp-to-jpg',
    name: 'WebP to JPG',
    label: 'Expand',
    description: 'Convert WebP to JPG for better compatibility.',
    icon: 'webp-jpg',
    inputFormats: ['webp'],
    outputFormat: 'jpg',
    category: 'image',
    apiEndpoint: '/api/convert',
    color: 'pink',
  },
  {
    id: 'png-to-jpg',
    name: 'PNG to JPG',
    label: 'Transform',
    description: 'Convert PNG images to JPG format.',
    icon: 'png-jpg',
    inputFormats: ['png'],
    outputFormat: 'jpg',
    category: 'image',
    apiEndpoint: '/api/convert',
    color: 'cyan',
  },
  {
    id: 'jpg-to-png',
    name: 'JPG to PNG',
    label: 'Convert',
    description: 'Convert JPG to PNG with transparency support.',
    icon: 'jpg-png',
    inputFormats: ['jpg', 'jpeg'],
    outputFormat: 'png',
    category: 'image',
    apiEndpoint: '/api/convert',
    color: 'green',
  },
  {
    id: 'png-to-webp',
    name: 'PNG to WebP',
    label: 'Optimize',
    description: 'Convert PNG to WebP for web optimization.',
    icon: 'png-webp',
    inputFormats: ['png'],
    outputFormat: 'webp',
    category: 'image',
    apiEndpoint: '/api/convert',
    color: 'blue',
  },
  {
    id: 'background-eraser',
    name: 'Background Eraser',
    label: 'Remove',
    description: 'Remove background from images automatically.',
    icon: 'eraser',
    inputFormats: ['jpg', 'jpeg', 'png', 'webp'],
    outputFormat: 'png',
    category: 'image',
    apiEndpoint: '/api/remove-bg',
    color: 'violet',
  },
  // Document Converters (5)
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    label: 'Export',
    description: 'Convert Word documents (DOC, DOCX) to PDF format.',
    icon: 'word-pdf',
    inputFormats: ['doc', 'docx'],
    outputFormat: 'pdf',
    category: 'document',
    apiEndpoint: '/api/convert/word-to-pdf',
    color: 'blue',
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    label: 'Extract',
    description: 'Convert PDF documents to editable Word files.',
    icon: 'pdf-word',
    inputFormats: ['pdf'],
    outputFormat: 'docx',
    category: 'document',
    apiEndpoint: '/api/convert/pdf-to-word',
    color: 'indigo',
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    label: 'Table',
    description: 'Convert Excel spreadsheets to PDF documents.',
    icon: 'excel-pdf',
    inputFormats: ['xls', 'xlsx'],
    outputFormat: 'pdf',
    category: 'document',
    apiEndpoint: '/api/convert/excel-to-pdf',
    color: 'green',
  },
  {
    id: 'ppt-to-pdf',
    name: 'PPT to PDF',
    label: 'Slide',
    description: 'Convert PowerPoint presentations to PDF.',
    icon: 'ppt-pdf',
    inputFormats: ['ppt', 'pptx'],
    outputFormat: 'pdf',
    category: 'document',
    apiEndpoint: '/api/convert/ppt-to-pdf',
    color: 'red',
  },
  {
    id: 'txt-to-pdf',
    name: 'Text to PDF',
    label: 'Write',
    description: 'Convert plain text files to PDF format.',
    icon: 'txt-pdf',
    inputFormats: ['txt'],
    outputFormat: 'pdf',
    category: 'document',
    apiEndpoint: '/api/convert/txt-to-pdf',
    color: 'teal',
  },
  // Video Converters (4)
  {
    id: 'mp4-to-webm',
    name: 'MP4 to WebM',
    label: 'Stream',
    description: 'Convert MP4 videos to WebM for smaller streaming-friendly files.',
    icon: 'mp4-webm',
    inputFormats: ['mp4'],
    outputFormat: 'webm',
    category: 'video',
    apiEndpoint: '/api/convert/media',
    color: 'cyan',
  },
  {
    id: 'avi-to-mp4',
    name: 'AVI to MP4',
    label: 'Modernize',
    description: 'Convert legacy AVI videos to modern MP4 format.',
    icon: 'video-convert',
    inputFormats: ['avi'],
    outputFormat: 'mp4',
    category: 'video',
    apiEndpoint: '/api/convert/media',
    color: 'orange',
  },
  {
    id: 'mov-to-mp4',
    name: 'MOV to MP4',
    label: 'Convert',
    description: 'Convert Apple QuickTime MOV files to widely compatible MP4.',
    icon: 'video-convert',
    inputFormats: ['mov'],
    outputFormat: 'mp4',
    category: 'video',
    apiEndpoint: '/api/convert/media',
    color: 'pink',
  },
  {
    id: 'mkv-to-webm',
    name: 'MKV to WebM',
    label: 'Streamline',
    description: 'Convert MKV videos to WebM for web-ready streaming.',
    icon: 'video-convert',
    inputFormats: ['mkv'],
    outputFormat: 'webm',
    category: 'video',
    apiEndpoint: '/api/convert/media',
    color: 'violet',
  },
  // Audio Converters (5)
  {
    id: 'mp3-to-wav',
    name: 'MP3 to WAV',
    label: 'Quality',
    description: 'Convert compressed MP3 to uncompressed WAV audio.',
    icon: 'audio-convert',
    inputFormats: ['mp3'],
    outputFormat: 'wav',
    category: 'audio',
    apiEndpoint: '/api/convert/media',
    color: 'green',
  },
  {
    id: 'wav-to-mp3',
    name: 'WAV to MP3',
    label: 'Compact',
    description: 'Convert uncompressed WAV to space-saving MP3 format.',
    icon: 'audio-convert',
    inputFormats: ['wav'],
    outputFormat: 'mp3',
    category: 'audio',
    apiEndpoint: '/api/convert/media',
    color: 'blue',
  },
  {
    id: 'mp3-to-aac',
    name: 'MP3 to AAC',
    label: 'Upgrade',
    description: 'Convert MP3 to AAC for better quality at lower bitrates.',
    icon: 'audio-convert',
    inputFormats: ['mp3'],
    outputFormat: 'aac',
    category: 'audio',
    apiEndpoint: '/api/convert/media',
    color: 'fuchsia',
  },
  {
    id: 'mp3-to-ogg',
    name: 'MP3 to OGG',
    label: 'Open',
    description: 'Convert MP3 to free and open OGG Vorbis format.',
    icon: 'audio-convert',
    inputFormats: ['mp3'],
    outputFormat: 'ogg',
    category: 'audio',
    apiEndpoint: '/api/convert/media',
    color: 'amber',
  },
  {
    id: 'mp4-to-mp3',
    name: 'Video to MP3',
    label: 'Extract',
    description: 'Extract audio track from video and save as MP3.',
    icon: 'video-mp3',
    inputFormats: ['mp4', 'avi', 'mov', 'mkv', 'webm'],
    outputFormat: 'mp3',
    category: 'audio',
    apiEndpoint: '/api/convert/media',
    color: 'rose',
  },
];

export function getToolById(id: string): Tool | undefined {
  return TOOLS.find(tool => tool.id === id);
}

export function getToolsByCategory(category: Tool['category']): Tool[] {
  return TOOLS.filter(tool => tool.category === category);
}