import { Tool } from './types';

export const toolColors: Record<string, { light: string; dark: string; gradient: string }> = {
  purple: { light: 'rgba(139, 92, 246, 0.3)', dark: '#7c3aed', gradient: 'linear-gradient(135deg, #8b5cf6, #7c3aed)' },
  orange: { light: 'rgba(249, 115, 22, 0.3)', dark: '#ea580c', gradient: 'linear-gradient(135deg, #f97316, #ea580c)' },
  pink: { light: 'rgba(236, 72, 153, 0.3)', dark: '#db2777', gradient: 'linear-gradient(135deg, #ec4899, #db2777)' },
  cyan: { light: 'rgba(6, 182, 212, 0.3)', dark: '#0891b2', gradient: 'linear-gradient(135deg, #06b6d4, #0891b2)' },
  green: { light: 'rgba(16, 185, 129, 0.3)', dark: '#059669', gradient: 'linear-gradient(135deg, #10b981, #059669)' },
  blue: { light: 'rgba(59, 130, 246, 0.3)', dark: '#2563eb', gradient: 'linear-gradient(135deg, #3b82f6, #2563eb)' },
  red: { light: 'rgba(239, 68, 68, 0.3)', dark: '#dc2626', gradient: 'linear-gradient(135deg, #ef4444, #dc2626)' },
  yellow: { light: 'rgba(234, 179, 8, 0.3)', dark: '#ca8a04', gradient: 'linear-gradient(135deg, #eab308, #ca8a04)' },
  emerald: { light: 'rgba(16, 185, 129, 0.3)', dark: '#059669', gradient: 'linear-gradient(135deg, #10b981, #059669)' },
  violet: { light: 'rgba(139, 92, 246, 0.3)', dark: '#7c3aed', gradient: 'linear-gradient(135deg, #8b5cf6, #7c3aed)' },
  indigo: { light: 'rgba(99, 102, 241, 0.3)', dark: '#4f46e5', gradient: 'linear-gradient(135deg, #6366f1, #4f46e5)' },
  teal: { light: 'rgba(20, 184, 166, 0.3)', dark: '#0d9488', gradient: 'linear-gradient(135deg, #14b8a6, #0d9488)' },
};

export const TOOLS: Tool[] = [
  // Image Converters (7)
  {
    id: 'image-compress',
    name: 'Image Compress',
    label: 'Squeeze',
    description: 'Reduce image file size by up to 80% while maintaining visual quality. Supports JPG, PNG, WebP, and GIF with adjustable compression levels — processed entirely in your browser.',
    icon: 'compress',
    inputFormats: ['jpg', 'jpeg', 'png', 'webp', 'gif'],
    outputFormat: 'jpg',
    category: 'image',
    apiEndpoint: '/api/convert',
    color: 'purple',
  },
  {
    id: 'jpg-to-webp',
    name: 'JPG to WebP',
    label: 'Compress',
    description: 'Convert JPG images to WebP format for 25-34% smaller file sizes with identical quality. Ideal for web optimization and faster page loads. No server upload needed.',
    icon: 'jpg-webp',
    inputFormats: ['jpg', 'jpeg'],
    outputFormat: 'webp',
    category: 'image',
    apiEndpoint: '/api/convert',
    color: 'orange',
  },
  {
    id: 'webp-to-jpg',
    name: 'WebP to JPG',
    label: 'Expand',
    description: 'Convert WebP images to universally compatible JPG format. Perfect for sharing on platforms that don\'t support WebP or for editing in legacy software. Browser-based, zero uploads.',
    icon: 'webp-jpg',
    inputFormats: ['webp'],
    outputFormat: 'jpg',
    category: 'image',
    apiEndpoint: '/api/convert',
    color: 'pink',
  },
  {
    id: 'png-to-jpg',
    name: 'PNG to JPG',
    label: 'Transform',
    description: 'Convert PNG images to JPG with adjustable quality settings. Reduces file size significantly by removing transparency. All processing happens locally in your browser.',
    icon: 'png-jpg',
    inputFormats: ['png'],
    outputFormat: 'jpg',
    category: 'image',
    apiEndpoint: '/api/convert',
    color: 'cyan',
  },
  {
    id: 'jpg-to-png',
    name: 'JPG to PNG',
    label: 'Convert',
    description: 'Convert JPG images to PNG format with lossless quality and transparency support. Perfect for graphics, logos, and images that need alpha channels. Client-side processing.',
    icon: 'jpg-png',
    inputFormats: ['jpg', 'jpeg'],
    outputFormat: 'png',
    category: 'image',
    apiEndpoint: '/api/convert',
    color: 'green',
  },
  {
    id: 'png-to-webp',
    name: 'PNG to WebP',
    label: 'Optimize',
    description: 'Convert PNG to WebP for modern web optimization. Achieve smaller file sizes with superior compression while retaining lossless quality. Zero server uploads.',
    icon: 'png-webp',
    inputFormats: ['png'],
    outputFormat: 'webp',
    category: 'image',
    apiEndpoint: '/api/convert',
    color: 'blue',
  },
  {
    id: 'background-eraser',
    name: 'Background Eraser',
    label: 'Remove',
    description: 'Remove backgrounds from images automatically using AI-powered detection. Outputs transparent PNG files. Works with JPG, PNG, and WebP — processed entirely in your browser for total privacy.',
    icon: 'eraser',
    inputFormats: ['jpg', 'jpeg', 'png', 'webp'],
    outputFormat: 'png',
    category: 'image',
    apiEndpoint: '/api/remove-bg',
    color: 'violet',
  },
  // Document Converters (5)
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    label: 'Export',
    description: 'Convert Word documents (DOC, DOCX) to PDF format with preserved formatting, fonts, and layout. Secure server-side processing with automatic file deletion after conversion.',
    icon: 'word-pdf',
    inputFormats: ['doc', 'docx'],
    outputFormat: 'pdf',
    category: 'document',
    apiEndpoint: '/api/convert/word-to-pdf',
    color: 'blue',
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    label: 'Extract',
    description: 'Convert PDF documents to fully editable Word files (DOCX). Preserves text, images, tables, and formatting for easy modification. Secure API processing with auto-delete.',
    icon: 'pdf-word',
    inputFormats: ['pdf'],
    outputFormat: 'docx',
    category: 'document',
    apiEndpoint: '/api/convert/pdf-to-word',
    color: 'indigo',
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    label: 'Table',
    description: 'Convert Excel spreadsheets (XLS, XLSX) to PDF documents with accurate table formatting, charts, and cell styling. Enterprise-grade secure API with automatic file cleanup.',
    icon: 'excel-pdf',
    inputFormats: ['xls', 'xlsx'],
    outputFormat: 'pdf',
    category: 'document',
    apiEndpoint: '/api/convert/excel-to-pdf',
    color: 'green',
  },
  {
    id: 'ppt-to-pdf',
    name: 'PPT to PDF',
    label: 'Slide',
    description: 'Convert PowerPoint presentations (PPT, PPTX) to PDF format while preserving slide layouts, images, and animations as static pages. Secure server processing.',
    icon: 'ppt-pdf',
    inputFormats: ['ppt', 'pptx'],
    outputFormat: 'pdf',
    category: 'document',
    apiEndpoint: '/api/convert/ppt-to-pdf',
    color: 'red',
  },
  {
    id: 'txt-to-pdf',
    name: 'Text to PDF',
    label: 'Write',
    description: 'Convert plain text files to professionally formatted PDF documents. Supports custom formatting options. Fast, secure conversion via our API.',
    icon: 'txt-pdf',
    inputFormats: ['txt'],
    outputFormat: 'pdf',
    category: 'document',
    apiEndpoint: '/api/convert/txt-to-pdf',
    color: 'teal',
  },
  // Video Converters (4)
  {
    id: 'mp4-to-webm',
    name: 'MP4 to WebM',
    label: 'Stream',
    description: 'Convert MP4 videos to WebM format for smaller, streaming-friendly files. WebM offers better compression for web playback. Secure API processing with automatic file deletion.',
    icon: 'mp4-webm',
    inputFormats: ['mp4'],
    outputFormat: 'webm',
    category: 'video',
    apiEndpoint: '/api/convert/media',
    color: 'cyan',
  },
  {
    id: 'avi-to-mp4',
    name: 'AVI to MP4',
    label: 'Modernize',
    description: 'Convert legacy AVI video files to modern MP4 format with H.264 encoding. Better compression, wider compatibility, and smaller file sizes. Secure server-side conversion.',
    icon: 'video-convert',
    inputFormats: ['avi'],
    outputFormat: 'mp4',
    category: 'video',
    apiEndpoint: '/api/convert/media',
    color: 'orange',
  },
  {
    id: 'mov-to-mp4',
    name: 'MOV to MP4',
    label: 'Convert',
    description: 'Convert Apple QuickTime MOV files to universally compatible MP4 format. Maintains video quality while improving compatibility across all devices and platforms.',
    icon: 'video-convert',
    inputFormats: ['mov'],
    outputFormat: 'mp4',
    category: 'video',
    apiEndpoint: '/api/convert/media',
    color: 'pink',
  },
  {
    id: 'mkv-to-webm',
    name: 'MKV to WebM',
    label: 'Streamline',
    description: 'Convert MKV Matroska video files to WebM format optimized for web streaming. Reduces file size while maintaining quality. Secure API processing.',
    icon: 'video-convert',
    inputFormats: ['mkv'],
    outputFormat: 'webm',
    category: 'video',
    apiEndpoint: '/api/convert/media',
    color: 'violet',
  },
  // Audio Converters (5)
  {
    id: 'mp3-to-wav',
    name: 'MP3 to WAV',
    label: 'Quality',
    description: 'Convert compressed MP3 audio to uncompressed WAV format for maximum audio quality. Ideal for audio editing, mastering, and professional production workflows.',
    icon: 'audio-convert',
    inputFormats: ['mp3'],
    outputFormat: 'wav',
    category: 'audio',
    apiEndpoint: '/api/convert/media',
    color: 'green',
  },
  {
    id: 'wav-to-mp3',
    name: 'WAV to MP3',
    label: 'Compact',
    description: 'Convert uncompressed WAV audio files to space-saving MP3 format with configurable bitrate. Reduces file size by up to 90% while maintaining good audio quality.',
    icon: 'audio-convert',
    inputFormats: ['wav'],
    outputFormat: 'mp3',
    category: 'audio',
    apiEndpoint: '/api/convert/media',
    color: 'blue',
  },
  {
    id: 'mp3-to-aac',
    name: 'MP3 to AAC',
    label: 'Upgrade',
    description: 'Convert MP3 audio to AAC format for better sound quality at equivalent bitrates. AAC is the standard for Apple Music, YouTube, and modern streaming platforms.',
    icon: 'audio-convert',
    inputFormats: ['mp3'],
    outputFormat: 'aac',
    category: 'audio',
    apiEndpoint: '/api/convert/media',
    color: 'fuchsia',
  },
  {
    id: 'mp3-to-ogg',
    name: 'MP3 to OGG',
    label: 'Open',
    description: 'Convert MP3 audio to free and open OGG Vorbis format. No licensing fees, excellent quality, and wide support in open-source media players and games.',
    icon: 'audio-convert',
    inputFormats: ['mp3'],
    outputFormat: 'ogg',
    category: 'audio',
    apiEndpoint: '/api/convert/media',
    color: 'amber',
  },
  {
    id: 'mp4-to-mp3',
    name: 'Video to MP3',
    label: 'Extract',
    description: 'Extract audio tracks from video files (MP4, AVI, MOV, MKV, WebM) and save as high-quality MP3. Perfect for extracting music, podcasts, or lectures from video.',
    icon: 'video-mp3',
    inputFormats: ['mp4', 'avi', 'mov', 'mkv', 'webm'],
    outputFormat: 'mp3',
    category: 'audio',
    apiEndpoint: '/api/convert/media',
    color: 'rose',
  },
];

export function getToolById(id: string): Tool | undefined {
  return TOOLS.find(tool => tool.id === id);
}

export function getToolsByCategory(category: Tool['category']): Tool[] {
  return TOOLS.filter(tool => tool.category === category);
}